### ISSUE TITLE
ActiveXObject.set

### ISSUE THREAD

**Issue by skacurt** [zspitz/activex-js-helpers#4]
Hi.

I would like to point out 3 problems of the `ActiveXObject.set` method along with solution suggestions.

https://github.com/zspitz/activex-js-helpers/blob/87d718b2beccc7376f7d2879e646e0f6efaef889/activex-js-helpers.js#L78-L83

1. `propertyName` enables malicious code execution.

    `eval('obj[propertyName] ...` would be sufficient.

2. When the `parameterString` is empty (`parameters = []`) the expression to be run becomes an assign to function call so an error occurs. 

    Assignments with no parameters should also be supported.

3. `eval` works almost as fast as native call on web browsers (IE, HTA) however it's terribly slow (~40 times on my machine) on non-browser environments such as WSH, MSScriptControl, ASP Classic. 

    Apparently the engine in web browser environment has its own `eval` optimization but the others lack that. 

   As a workaround, this can be handled better with native expressions by using [conditional compilation](http://web.archive.org/web/20171207171845/https://docs.microsoft.com/en-us/scripting/javascript/reference/at-cc-on-statement-javascript) for properties with up to a certain number of parameters (to reduce hard-coded expressions), 0 to 3 for example. A fallback to `eval` would be sufficient for properties having more than 3 parameters which are very rare.

**Comment by zspitz** [comment]
Changes have been merged and uploaded to NPM.
